include-and-override=portal-developer.properties

jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://database:3306/lportal
jdbc.default.username=lportal
jdbc.default.password=lportal

setup.wizard.enabled=false
terms.of.use.required=false
company.default.name=Liferay
company.default.web.id=liferay.com

company.default.locale=pt_BR,en_US
company.default.time.zone=GMT-3

company.login.prepopulate.domain=false
company.security.auth.type=emailAddress
company.security.strangers=false
company.security.send.password.reset.link=false
users.reminder.queries.custom.question.enabled=false
users.reminder.queries.enabled=false

layout.user.private.layouts.auto.create=false
layout.user.private.layouts.enabled=false
layout.user.public.layouts.auto.create=false
layout.user.public.layouts.enabled=false

blogs.pingback.enabled=false
blogs.ping.google.enabled=false

com.liferay.portal.servlet.filters.sso.cas.CASFilter=false
com.liferay.portal.servlet.filters.sso.ntlm.NTLMFilter=false
com.liferay.portal.servlet.filters.sso.ntlm.NTLMPOSTFilter=false
com.liferay.portal.servlet.filters.sso.opensso.OpenSSOFilter=false
com.liferay.portal.sharepoint.SharepointFILTER=false

locales=pt_BR,en_US
locales.enabled=pt_BR,en_US

session.tracker.memory.enabled=false
hibernate.jdbc.batch_size=200
buffered.increment.standby.queue.threshold=10000
buffered.increment.standby.time.upper.limit=60
counter.increment=5000

web.server.display.node=false
dl.store.impl=com.liferay.portal.store.file.system.AdvancedFileSystemStore
redirect.url.security.mode=domain
jsonws.web.service.api.discoverable=false
javascript.single.page.application.enabled=false
company.security.strangers.verify=false

upgrade.database.auto.run=false

captcha.enforce.disabled=true

index.search.limit=30000